// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// .env dosyasından değişkenleri al (Vite için import.meta.env kullanılır)
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Hata kontrolü: Değişkenler tanımlı mı?
if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Supabase URL veya Anon Key ortam değişkenlerinde (VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY) tanımlı değil!');
  // Burada daha kullanıcı dostu bir hata mesajı gösterebilir veya uygulamayı durdurabilirsiniz.
  // Şimdilik basit bir hata fırlatalım.
  throw new Error("Supabase environment variables are not set.");
}

// Supabase istemcisini oluştur ve dışa aktar
// Database tipi generic olarak eklenirse, RLS ve diğer Supabase özelliklerinden daha iyi tip güvenliği alınır.
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);